### PR TITLE
added a leaflet map to the modal order window.  

### PR DESCRIPTION
**Pull request by banders**
there are a couple things left to do to finish the modal order window: 

1. the functionality to fetch a resource which provides the maximum downloadable area for the dataset isn't yet implemented (for now I just assume a hard-coded max area).  

2. the 'place order' button currently doesn't do anything on click.

### CODE REVIEW

**Review by JessicaInTime — CHANGES_REQUESTED** [review]
@banders should add yourself to the author list in files likes edc_mow.js

**Comment by JessicaInTime** [comment]
@banders you should use the fanstatic directory for static resources and load via resource tag https://github.com/banders/ckanext-bcgov/blob/33d6c7f56cfd58710c98c4218b665ce73ccce5b6/ckanext/bcgov/templates/snippets/edc_mow.html#L7-L9

eg. https://github.com/banders/ckanext-bcgov/blob/33d6c7f56cfd58710c98c4218b665ce73ccce5b6/ckanext/bcgov/templates/snippets/edc_mow.html#L102-L103

**Comment by JessicaInTime** [comment]
@banders you can also remove the example data passing to js module: https://github.com/banders/ckanext-bcgov/blob/33d6c7f56cfd58710c98c4218b665ce73ccce5b6/ckanext/bcgov/templates/snippets/edc_mow.html#L3

**Comment by JessicaInTime** [comment]
@banders but the main question i have is, why is all this leaflet js code being included? Are you not able to use what's provided by ckan?

**Comment by banders** [comment]
Sounds like you think CKAN may include leaflet's js and css files already...?  I didn't realize that.  Any idea where those might be?

**Comment by JessicaInTime** [comment]
@banders my mistake thinking that ckan provided leaflet, the map views in ckan are provided by the ckanext-geoview extension, i will have a look for an example what it does to get the necessary resources

**Comment by JessicaInTime** [comment]
@banders ok, so geoview ext has a couple of defined resource loading vars here: https://github.com/ckan/ckanext-geoview/blob/master/ckanext/geoview/public/resource.config

you would call them like this in a template `{% resource 'ckanext-geoview/{geojson|openlayers2|wmts}' %}`

however, i don't know if those groups have everything you need for the map view.

**Comment by banders** [comment]
I see that the geoview extension has some leaflet libs there.  It's the same version of leaflet that I need.  To confirm: you think it's okay to introduce a dependency on the geoview extension?

There is one library (leaflet-draw) that I require which is not included in geoview.  Okay if I include that in ckanext-bcgov?

**Comment by JessicaInTime** [comment]
@banders for the dependency, yes it should be fine, the geoview ext will be (should be) always in our env. Just for an added check, there should be a helper function or something available in templates that you can get a list of the loaded extensions and check to see if geoview is in the list, and handle any issues there.

As for the leaflet-draw, if you need it, you need it =). I recommend using the fanstatic way of loading it, rather then doing <script />

**Pull request merged**
